### ISSUE TITLE
DDIM time delay

### ISSUE THREAD

**Issue by GYDDHPY** [lucidrains/bit-diffusion#10]
It seems the time delay in DDIM is at wrong place, as the delay is applied after releated operations are done.

https://github.com/lucidrains/bit-diffusion/blob/7a9b3ef518d405eea2b2a04de1c7515447a9286b/bit_diffusion/bit_diffusion.py#L501-L531

**Comment by lucidrains** [comment]
oops, yes, should be fixed! thanks!
